baseURL: 'https://bsidescincy.org/'
languageCode: en-us
title: BSides Cincinnati
theme: roxo
summarylength: 25
menu:
  nav:
    - name: Home
      url: ''
      weight: 1
    - name: Register
      url: register
      weight: 2
    - name: Sponsors
      url: sponsors
      weight: 3
    - name: Archives
      url: archives
      weight: 4
    - name: Announcements
      url: announcements
      weight: 5
    - name: About
      url: about
      weight: 6
    - name: 'Contact Us'
      url: contact
      weight: 7
params:
  logo: 'images/bsideslogo.png'
  footerLogo: 'images/bsideslogo-white.png'
  dateFormat: 26 FEB 1994
  description: BSides Cincinnati
  custom_css: 
    - "css/override.css"
  author: Ezra Buckingham
  googleAnalitycsID: Your ID
  navAction:
    status: true
    name: 'Contact Us'
    url: contact
  
  banner:
    enable: true
    background_image: images/backgrounds/hero-background.jpeg
    heading: A Cybersecurity conference focused on building the next generation of Cyber professionals
    tagline: "BSides Cincinnati is..."
    primary_button: Register Now
    primary_button_url: portfolio
    secondary_button: Submit a Talk
    secondary_button_url: contact

  call_to_action:
    enable: true
    background_image: images/backgrounds/cta-background.jpg
    title: "LET'S WORK TOGETHER"
    primary_button: Become a Sponsor
    primary_button_url: 'sponsors' # TODO
    secondary_button: Submit a Talk
    secondary_button_url: 'registration' # TODO
  footer:
    contactInfo:
      title: Contact Info
      address: '520 Vine St<br>Cincinnati, OH 45202'
      phone: 513-000-0000
      email: bsidescincy@gmail.com
    sitemap:
      title: Sitemap
      link:
        - name: About BSides Cincy
          url: about
        - name: Past Conferences
          url: archives
        - name: Announcements
          url: announcements
        - name: Contact
          url: contact
    social:
      link:
        - icon: 'fa-twitter'
          url: 'https://twitter.com/bsidescincy/'
        - icon: 'fa-envelope'
          url: 'mailto:bsidescincy@gmail.com'
    service:
      title: 'We are building the future'
      description: cultivate the future generation of Cybersecurity professionals through exposure to the best and brightest
