name: bsidescincy-deploy-actions
run-name: Deployment action run for ${{ github.ref_name }}

on: 
  push:
    branches: 
      - 'main'
      - 'prod'
  pull_request:

# permissions:
#   id-token: write
#   contents: read

jobs:
  deploy-site:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout site source
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Modify baseURL in config if not prod deploy
        if: github.ref_name != 'prod'
        run: sed 's/bsidescincy.org/bsidescincy-test.s3-website.us-east-2.amazonaws.com/g' config.yml > config.yml

      - name: Build hugo site
        run: hugo --minify

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_BSIDES_ROLE_ARN }}
          role-session-name: GithubDeploy_${{ github.ref_name }}
          aws-region: us-east-2

      - name: Deploying to staging bucket
        if: github.ref_name == 'main'
        run: aws s3 sync ./public/ s3://${{ secrets.AWS_BSIDES_STAGING_BUCKET }}/

      - name: Deploying to prod bucket
        if: github.ref_name == 'prod'
        run: aws s3 sync ./public/ s3://${{ secrets.AWS_BSIDES_PROD_BUCKET }}/
